name: Automatic Build On Push
on: 
  push:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    name: Build Windows Executable
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - id: find_yyp
        name: Find the yyp file
        run: |
          $yyp = Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter *.yyp
          Write-Output "YYP file found at: $yyp"
          "yyp-path=$yyp" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      - name: use Igor Setup
        uses: bscotch/igor-setup@v2
        id: igor
        with:
          target-yyp: ${{ steps.find_yyp.outputs.yyp-path }}
          access-key: ${{ secrets.GM_ACCESS_KEY }}
      - name: use Igor Build
        uses: bscotch/igor-build@v1
        id: build
        with:
          yyc: false
          yyp-path: ${{ steps.find_yyp.outputs.yyp-path }}
          user-dir: ${{ steps.igor.outputs.user-dir }}
      - name: upload-build
        uses: actions/upload-artifact@v4
        with:
          name: igor-build-windows
          path: ${{ steps.build.outputs.out-dir }}
          retention-days: 1
  run-tests:
    name: Run Executable
    needs: build
    runs-on: windows-2022
    steps:
      - name: Download Igor Build
        uses: actions/download-artifact@v4
        with:
          name: igor-build-windows
          path: ./ci_tests
      - name: Run Executable
        shell: pwsh
        run: |
          Set-Location ./ci_tests
          Expand-Archive -Path ./arithmancer.zip -DestinationPath ./arithmancer
          Set-Location ./arithmancer
          Start-Process -FilePath ./Arithmancer.exe `
            -NoNewWindow `
            -RedirectStandardOutput ./output.log `
            -RedirectStandardError ./errors.log
          Start-Sleep 30
          Get-ChildItem .
